<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
{ce:build:extract file=build_path."../../config.php" vars="SHORTCODE_NAME|SHORTCODE_VERSION"}
<head>
    <title>{SHORTCODE_NAME} - {SHORTCODE_VERSION} - Docs {if title}- {title}{/if}</title>
    
    <link href="http://fonts.googleapis.com/css?family=Puritan:400,700" rel="stylesheet" type="text/css">

    <link rel="stylesheet" media="screen, projection" href="{root_url}assets/styles/reset.css" />
    <link rel="stylesheet" media="screen, projection" href="{root_url}assets/styles/screen.css" />
    <link rel="stylesheet" media="screen, projection" href="{root_url}assets/styles/docs.css" />
    
    <!-- SYNTAXHIGHLIGHTER -->
    <script type="text/javascript" src="{root_url}assets/lib/syntaxhighlighter/js/shCore.js"></script>
    <script type="text/javascript" src="{root_url}assets/lib/syntaxhighlighter/js/shBrushJScript.js"></script>
    <script type="text/javascript" src="{root_url}assets/lib/syntaxhighlighter/js/shBrushXml.js"></script>
    <script type="text/javascript" src="{root_url}assets/lib/syntaxhighlighter/js/shBrushPhp.js"></script>
    <link href="{root_url}assets/lib/syntaxhighlighter/css/shCore.css" rel="stylesheet" type="text/css" />
    <link href="{root_url}assets/lib/syntaxhighlighter/css/shThemeMidnight.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript">
         SyntaxHighlighter.all()
    </script>
    <script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-21302173-2']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
    </script>
</head>
<body class="no-js">
<!-- This file was generated by the CELL build templates command. Do not modify this file directly. -->

<div class="section-content-wrapper grid-group">
    <ul class="nav-global-top grid-group">
        <li>
            <h1 class="text-replace nav-logo-header"><a href="http://metasushi.com/">MetaSushi</a></h1>
        </li>
        <li><a class="nav-2-prod" href="http://metasushi.com/products">Products</a></li>
        <li><a class="nav-3-doc" href="http://metasushi.com/documentation">Documentation</a></li>
        <li><a class="nav-4-links" href="http://metasushi.com/blog">Blog</a></li>
        <li><span class="nav-5-con" href="index.html">&nbsp;</span></li>
        <li class="nav-right-end-search">

            <form action="http://metasushi.com/search/" method="get">
                <input type="submit" value="">
                <input type="text" name="q" value="" placeholder="Search...">
            </form>

        </li>
    </ul>
    <div class="section-content-wide content-box" id="documentation">
        {if index != "yes"}
        <!-- <a href="{root_url}">&larr; {SHORTCODE_NAME} Documentation Index</a> -->
        {/if}

{/ce:build:extract}
